// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDseT4HgKbVv_NDmTjnTmXCo5t1ytfxJ10',
    appId: '1:650074123699:web:9df61d8ce1aef434d52fc6',
    messagingSenderId: '650074123699',
    projectId: 'kkubeo-eaacc',
    authDomain: 'kkubeo-eaacc.firebaseapp.com',
    storageBucket: 'kkubeo-eaacc.firebasestorage.app',
    measurementId: 'G-R66N0X57XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKmW0FWqY9PnmPwoFzwQH-JaA30kP0hWA',
    appId: '1:650074123699:android:524752b48037fa49d52fc6',
    messagingSenderId: '650074123699',
    projectId: 'kkubeo-eaacc',
    storageBucket: 'kkubeo-eaacc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDseT4HgKbVv_NDmTjnTmXCo5t1ytfxJ10',
    appId: '1:650074123699:web:65e2f38aec0f67f2d52fc6',
    messagingSenderId: '650074123699',
    projectId: 'kkubeo-eaacc',
    authDomain: 'kkubeo-eaacc.firebaseapp.com',
    storageBucket: 'kkubeo-eaacc.firebasestorage.app',
    measurementId: 'G-4BXSDFBS9W',
  );
}
